### PR TITLE
made Navigator Equatable

### PR DESCRIPTION
**Pull request by 3a4oT**
I use SwiftUIRouter with Composable architecture to make things easier I've added Equatable conformance to Navigator so it can be used in` TCA` action or state.
- made Navigator Equatable
- added Tests

### CODE REVIEW

**Comment by frzi** [comment]
Interesting, I never considered making `Navigator` conform to `Equatable`. 

I'm not well-versed with Composable architecture in SwiftUI. Is initializing a new `Navigator` something that occurs? I'm curious whether a simple [instance comparison](https://developer.apple.com/documentation/swift/1538988) would suffice or not, instead of a deep comparison:
```swift
extension Navigator: Equatable {
	public func == (lhs: Navigator, rhs: Navigator) -> Bool {
		lhs === rhs
	}
}
```

Thanks!

**Comment by 3a4oT** [comment]
>  Is initializing a new Navigator something that occurs

Not really I just pass a reference to action when I need to navigate somewhere so I'm fine to simplify thing!

**Comment by 3a4oT** [comment]
Thanks! can I count on the new release any time soon?=)

**Comment by 3a4oT** [comment]
BTW. for some reason, I don't see these changes on the main branch. Am I missing something? cc @frzi

**Comment by frzi** [comment]
I've reorganized pieces a bit as I was going through the documentation. Rest assured [your changes](https://github.com/frzi/SwiftUIRouter/blob/main/Sources/Navigator.swift#L144) [are present](https://github.com/frzi/SwiftUIRouter/blob/main/Tests/SwiftUIRouterTests/SwiftUIRouterTests.swift#L7) in the main branch. 😉 

Currently going through some things to prepare for 1.1.0, looking what to include and what not. If there's a sense of urgency, you can tell Xcode to use the main branch instead of tagged releases in the meantime. 😉

**Comment by 3a4oT** [comment]
Yeah, seems tit was a false-positive ping!

**Pull request merged**
