### PR TITLE
Made `Navigator` initializer public. Added new init to `Router`

### PR DESCRIPTION
**Pull request by frzi**
Closes #23 and adds a new initializer to `Router`.

### CODE REVIEW

**Comment by matthewrobb** [comment]
Is there a timeline on this landing? I’d really like to set up my Navigator outside of the view hierarchy

**Comment by frzi** [comment]
This will be merged pretty soon. I'm still fiddling here and there and writing some (new) documentation. These changes (along with minor QoL improvements) should land in upcoming version (1.2.0). For the time being you can refer to the specific `dev/public-navigator` branch as described [in this issue](https://github.com/frzi/SwiftUIRouter/pull/23#issuecomment-899675288). 😄

**Comment by 3a4oT** [comment]
@frzi hello, do you have ETA on new release :) Is there anything which I can help with?

**Comment by frzi** [comment]
Oops! I got a bit sidetracked with a different project. I'll merge this now and release 1.2.0!

**Pull request merged**
